# Generated by Django 6.0 on 2026-02-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_extras',
            field=models.BooleanField(default=True, verbose_name='Mostrar sección extra'),
        ),
    ]
