# Generated by Django 6.0 on 2026-06-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_show_extras_to_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='history',
            field=models.TextField(blank=True, default='', help_text='Breve historia u origen del cóctel (se muestra en el menú digital).', verbose_name='Historia'),
        ),
    ]
