# Generated by Django 6.0 on 2026-06-26 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_seed_businesses'),
        ('products', '0004_category_business_product_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('min_select', models.PositiveSmallIntegerField(default=0, verbose_name='Mínimo a elegir')),
                ('max_select', models.PositiveSmallIntegerField(default=1, verbose_name='Máximo a elegir')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifier_groups', to='business.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Grupo de opciones',
                'verbose_name_plural': 'Grupos de opciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, help_text='Cuánto suma (o resta, si es negativo) esta opción al precio base.', max_digits=10, verbose_name='Precio adicional')),
                ('is_default', models.BooleanField(default=False, verbose_name='Preseleccionada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.modifiergroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Opción de grupo',
                'verbose_name_plural': 'Opciones de grupo',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('min_select_override', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mínimo (override)')),
                ('max_select_override', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Máximo (override)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='products.modifiergroup', verbose_name='Grupo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_links', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Grupo de opciones del producto',
                'verbose_name_plural': 'Grupos de opciones del producto',
                'ordering': ['display_order'],
                'unique_together': {('product', 'group')},
            },
        ),
    ]
