# Generated by Django 6.0 on 2025-12-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
    ]
