# Generated by Django 6.0 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_delivered_at_orderitem_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_numbers',
            field=models.JSONField(default=list, help_text='Números de mesa donde se atiende al cliente (1-5)', verbose_name='Números de mesa'),
        ),
    ]

