# Generated by Django 6.0 on 2025-01-XX XX:XX

from django.db import migrations, models


def set_default_table_number(apps, schema_editor):
    """Asigna un valor por defecto a los pedidos existentes"""
    Order = apps.get_model('orders', 'Order')
    # Actualizar todos los pedidos existentes con mesa 1 por defecto
    Order.objects.filter(table_number__isnull=True).update(table_number=1)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_table_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_numbers',
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(default=1, help_text='Número de mesa donde se atiende al cliente (1-5)', verbose_name='Número de mesa'),
        ),
        migrations.RunPython(set_default_table_number, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(help_text='Número de mesa donde se atiende al cliente (1-5)', verbose_name='Número de mesa'),
        ),
    ]

