# Generated by Django 6.0 on 2025-01-XX XX:XX

from django.db import migrations, models


def remove_default_table_numbers(apps, schema_editor):
    """Elimina el valor por defecto de 1 y lo pone en null para pedidos existentes"""
    Order = apps.get_model('orders', 'Order')
    # Cambiar los pedidos que tienen mesa 1 (probablemente el default) a null
    # Solo si fueron creados antes de que se implementara el campo obligatorio
    # Por seguridad, solo cambiamos los que tienen mesa 1 y fueron creados antes de la migración
    Order.objects.filter(table_number=1).update(table_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_table_numbers_add_order_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(blank=True, help_text='Número de mesa donde se atiende al cliente (1-5)', null=True, verbose_name='Número de mesa'),
        ),
        migrations.RunPython(remove_default_table_numbers, migrations.RunPython.noop),
    ]

