# Generated by Django 6.0 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_table_number_allow_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(blank=True, help_text='Número de mesa donde se atiende al cliente (0=Barra, 1-5=Mesas)', null=True, verbose_name='Número de mesa'),
        ),
    ]


