# Generated by Django 6.0 on 2026-01-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_table_number_allow_zero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(help_text='Número de la mesa (1, 2, 3, etc.)', unique=True, verbose_name='Número de mesa')),
                ('table_name', models.CharField(help_text='Nombre descriptivo de la mesa', max_length=50, verbose_name='Nombre')),
                ('visit_count', models.PositiveIntegerField(default=0, help_text='Cantidad de veces que se ha accedido a esta mesa', verbose_name='Visitas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['table_number'],
            },
        ),
    ]
