# Generated by Django 6.0 on 2026-01-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(help_text='Número de la mesa (0=Barra, 1-N=Mesas)', unique=True, verbose_name='Número de mesa'),
        ),
    ]
