# Generated by Django 6.0 on 2026-01-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_table_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Ruta de la página (ej: /, /menu, /contacto)', max_length=200, unique=True, verbose_name='Ruta')),
                ('page_name', models.CharField(help_text='Nombre descriptivo de la página', max_length=100, verbose_name='Nombre')),
                ('visit_count', models.PositiveIntegerField(default=0, help_text='Cantidad de veces que se ha accedido a esta página', verbose_name='Visitas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visita de página',
                'verbose_name_plural': 'Visitas de páginas',
                'ordering': ['-visit_count'],
            },
        ),
    ]
