# Generated by Django 6.0 on 2026-02-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='access_code',
            field=models.CharField(blank=True, help_text='Código de 4 caracteres para que el cliente consulte su pedido', max_length=4, verbose_name='Código de acceso'),
        ),
    ]
