# Generated by Django 6.0 on 2026-06-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_business_prep_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['floor', 'table_number'], 'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.table', verbose_name='Mesa'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_floor',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Piso de la mesa donde se atiende al cliente', null=True, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='table',
            name='floor',
            field=models.PositiveSmallIntegerField(default=2, help_text='Piso donde está ubicada la mesa o barra', verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(blank=True, help_text='Número de mesa dentro del piso (0=Barra, 1-N=Mesas)', null=True, verbose_name='Número de mesa'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_name',
            field=models.CharField(help_text='Nombre descriptivo de la mesa (ej: Mesa 1, Barra)', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(help_text='Número de la mesa dentro del piso (0=Barra, 1-N=Mesas)', verbose_name='Número de mesa'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('table_number', 'floor')},
        ),
    ]
