# Generated by Django 6.0 on 2026-07-04 21:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_backfill_order_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('3000.00'), help_text='Costo fijo del domicilio que se suma al total del pedido', max_digits=10, verbose_name='Tarifa de envío')),
                ('customer_ordering_enabled', models.BooleanField(default=True, help_text='Interruptor general para habilitar/pausar los pedidos a domicilio del cliente', verbose_name='Domicilios en línea activos')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de la tienda',
                'verbose_name_plural': 'Configuración de la tienda',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tarifa de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_reference',
            field=models.CharField(blank=True, help_text='Punto de referencia o indicaciones para el domiciliario', max_length=300, verbose_name='Referencia / indicaciones'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'En el local'), ('pickup', 'Para recoger'), ('delivery', 'Domicilio')], default='dine_in', max_length=20, verbose_name='Tipo de pedido'),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('staff', 'Staff'), ('customer', 'Cliente')], default='staff', help_text='staff = creado por el equipo; customer = pedido en línea del cliente', max_length=20, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
    ]
