# Generated by Django 6.0 on 2026-07-10 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_storesettings_order_delivery_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='is_open',
            field=models.BooleanField(default=True, help_text="Si está cerrado, el cliente ve el estado 'Cerrado' y no puede hacer pedidos.", verbose_name='Local abierto'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que se abrió/cerró el local.', null=True, verbose_name='Estado cambiado el'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Estado cambiado por'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='customer_ordering_enabled',
            field=models.BooleanField(default=False, help_text='Interruptor general para habilitar/pausar los pedidos a domicilio del cliente', verbose_name='Domicilios en línea activos'),
        ),
    ]
