# Generated by Django 6.0 on 2026-07-14 00:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_storesettings_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), help_text='Costo fijo del domicilio que se suma al total del pedido', max_digits=10, verbose_name='Tarifa de envío'),
        ),
    ]
