# Generated by Django 6.0 on 2026-07-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_storesettings_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('staff', 'Staff'), ('customer', 'Cliente'), ('whatsapp', 'WhatsApp')], default='staff', help_text='staff = creado por el equipo; customer = pedido en línea del cliente', max_length=20, verbose_name='Origen'),
        ),
    ]
