# Generated by Django 6.0 on 2026-08-11 14:26

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def copiar_radio_de_settings(apps, schema_editor):
    """Arranca el campo con el radio que hoy está vigente en el entorno.

    Hasta ahora el radio venía de la env DELIVERY_RADIUS_KM (ajustable en
    Railway sin deploy). Si allí hay un valor distinto del default, la fila de
    configuración debe nacer con ese, no con 1.5.
    """
    StoreSettings = apps.get_model('orders', 'StoreSettings')
    radio = Decimal(str(settings.DELIVERY_RADIUS_KM)).quantize(Decimal('0.01'))
    StoreSettings.objects.update(delivery_radius_km=radio)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Distancia máxima desde el local hasta donde se entrega a domicilio. La usan el checkout web, el agente de WhatsApp y el mapa de cobertura.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('50.00'))], verbose_name='Radio de domicilios (km)'),
        ),
        migrations.RunPython(copiar_radio_de_settings, migrations.RunPython.noop),
    ]
