# Generated by Django 6.0 on 2026-08-21 04:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_storesettings_delivery_radius_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='delivery_area',
            field=models.JSONField(blank=True, default=list, help_text='Figuras dibujadas en el mapa: lista de polígonos, cada uno una lista de puntos [longitud, latitud]. Si tiene contenido, manda sobre el radio; vacío ([]) vuelve al círculo. Se edita desde el dashboard.', verbose_name='Zona de domicilios (polígono)'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Distancia máxima desde el local hasta donde se entrega a domicilio. Solo se usa mientras no haya una zona dibujada en el mapa.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('50.00'))], verbose_name='Radio de domicilios (km)'),
        ),
    ]
