# Generated by Django 6.0 on 2026-08-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_storesettings_delivery_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='pickup_enabled',
            field=models.BooleanField(default=True, help_text='Independiente de los domicilios: con el domicilio pausado el cliente puede seguir encargando y pasar por su pedido al local.', verbose_name='Pedidos para recoger activos'),
        ),
    ]
