# Generated by Django 6.0 on 2026-08-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_storesettings_pickup_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Teléfono del cliente o, en pedidos de WhatsApp sin número, su BSUID de Meta', max_length=160, verbose_name='Teléfono'),
        ),
    ]
