# Generated by Django 6.0 on 2026-09-02 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_order_customer_phone_bsuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='opening_time',
            field=models.TimeField(default=datetime.time(13, 30), help_text='Solo informativa: es la hora que se le dice al cliente cuando escribe con el local cerrado. NO abre ni cierra nada (eso sigue siendo manual).', verbose_name='Hora de apertura habitual'),
        ),
    ]
