# Generated by Django 6.0 on 2026-09-04 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_storesettings_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='eta_max_minutes',
            field=models.PositiveSmallIntegerField(default=20, help_text='El otro extremo del rango. Igual al mínimo = un solo número.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='Demora máxima (minutos)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='eta_min_minutes',
            field=models.PositiveSmallIntegerField(default=10, help_text='Lo que normalmente tarda un pedido desde que se toma. Es lo que el agente de WhatsApp responde cuando preguntan cuánto se demora: una estimación, nunca una promesa.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='Demora mínima (minutos)'),
        ),
    ]
