# Generated by Django 6.0 on 2026-09-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_storesettings_eta_max_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok')], max_length=20, verbose_name='Red social')),
                ('source', models.CharField(choices=[('hero', 'Hero'), ('banner_descuento', 'Banner de descuento'), ('popup', 'Popup'), ('footer', 'Pie de página'), ('carta', 'Carta')], help_text='Lugar de la app desde donde se tocó el enlace', max_length=30, verbose_name='Origen')),
                ('date', models.DateField(help_text='Día local del clic', verbose_name='Fecha')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Clics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clic a red social',
                'verbose_name_plural': 'Clics a redes sociales',
                'ordering': ['-date', '-click_count'],
                'constraints': [models.UniqueConstraint(fields=('network', 'source', 'date'), name='unique_social_click_per_day')],
            },
        ),
    ]
