# Generated by Django 6.0 on 2026-09-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_socialclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notified_statuses',
            field=models.JSONField(blank=True, default=list, editable=False, help_text="Estados de los que ya se le avisó al cliente por WhatsApp. Un pedido puede retroceder (el equipo lo devuelve a la cocina) y sin esto el cliente recibe dos veces el mismo aviso: a Anyi le llegó 'entregado', contestó que aún no le entregaban, y le volvió a llegar media hora después", verbose_name='Estados ya avisados'),
        ),
    ]
