# Generated by Django 6.0 on 2026-09-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_notified_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='pickup_enabled',
        ),
    ]
