# Generated by Django 6.0 on 2026-09-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_remove_storesettings_pickup_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='ordering_changed_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que se prendieron o se apagaron los domicilios. Lo mira el vigía de WhatsApp para avisarle al cliente que se quedó sin domicilio mientras estaban apagados (ver whatsapp/domicilios.py).', null=True, verbose_name='Domicilios cambiados el'),
        ),
    ]
