# Generated by Django 6.0 on 2026-07-16 17:36

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0019_alter_order_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservations_enabled', models.BooleanField(default=False, help_text='Interruptor general para habilitar/pausar las reservas desde la app', verbose_name='Reservas en línea activas')),
                ('table_max_party', models.PositiveSmallIntegerField(default=6, help_text='Por encima de este número la reserva pasa a ser de grupo grande (con anticipo)', verbose_name='Personas máx. por reserva de mesa')),
                ('seats_per_table', models.PositiveSmallIntegerField(default=4, help_text='Se usa para estimar cuántas mesas necesita un grupo', verbose_name='Puestos por mesa')),
                ('max_reserved_tables_per_slot', models.PositiveSmallIntegerField(default=3, help_text='Tope de mesas reservadas a la vez por piso; el resto queda para walk-ins', verbose_name='Mesas reservables por piso y franja')),
                ('table_hold_minutes', models.PositiveSmallIntegerField(default=15, help_text='Minutos de gracia antes de liberar una mesa reservada que no llegó', verbose_name='Tolerancia de llegada (min)')),
                ('table_window_minutes', models.PositiveSmallIntegerField(default=120, help_text='Tiempo estimado que ocupa una mesa reservada, para calcular choques', verbose_name='Ventana estimada por reserva (min)')),
                ('reservable_from', models.TimeField(default=datetime.time(15, 0), help_text='Hora de llegada más temprana que se puede reservar', verbose_name='Reservas desde')),
                ('reservable_until', models.TimeField(default=datetime.time(21, 30), help_text='Hora de llegada más tardía que se puede reservar', verbose_name='Reservas hasta')),
                ('max_advance_days', models.PositiveSmallIntegerField(default=30, help_text='Hasta cuántos días en el futuro se puede reservar', verbose_name='Antelación máxima (días)')),
                ('group_deposit', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), help_text='Anticipo abonable al consumo para grupos que ocupan varias mesas', max_digits=10, verbose_name='Anticipo grupo grande')),
                ('vip_capacity', models.PositiveSmallIntegerField(default=15, verbose_name='Capacidad Sala VIP')),
                ('vip_room_table_count', models.PositiveSmallIntegerField(default=0, help_text='Cuántas mesas del pool del piso 3 quedan dentro de la Sala VIP y se bloquean al reservarla. 0 = la sala es un espacio aparte.', verbose_name='Mesas del piso 3 dentro de la sala')),
                ('vip_deposit', models.DecimalField(decimal_places=2, default=Decimal('40000.00'), help_text='Anticipo abonable al consumo para reservar la sala', max_digits=10, verbose_name='Anticipo Sala VIP')),
                ('vip_min_consumption_weekday', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=10, verbose_name='Consumo mínimo entre semana')),
                ('vip_min_consumption_weekend', models.DecimalField(decimal_places=2, default=Decimal('150000.00'), max_digits=10, verbose_name='Consumo mínimo viernes/sábado')),
                ('vip_slot_1_start', models.TimeField(default=datetime.time(15, 0), verbose_name='Turno tarde: inicio')),
                ('vip_slot_1_end', models.TimeField(default=datetime.time(18, 0), verbose_name='Turno tarde: fin')),
                ('vip_slot_2_start', models.TimeField(default=datetime.time(19, 0), verbose_name='Turno noche: inicio')),
                ('vip_slot_2_end', models.TimeField(default=datetime.time(23, 0), verbose_name='Turno noche: fin')),
                ('payment_instructions', models.TextField(default='Envía el anticipo por Nequi al 316 427 7879 y conserva el comprobante. Confirmamos tu reserva apenas verifiquemos el pago.', help_text='Se muestran al cliente al crear una reserva con anticipo', verbose_name='Instrucciones de pago del anticipo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de reservas',
                'verbose_name_plural': 'Configuración de reservas',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('table', 'Mesa'), ('group', 'Grupo grande'), ('vip_room', 'Sala VIP')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente de anticipo'), ('pending_review', 'En revisión'), ('confirmed', 'Confirmada'), ('seated', 'En la mesa'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No llegó')], default='confirmed', max_length=20, verbose_name='Estado')),
                ('source', models.CharField(choices=[('app', 'App'), ('whatsapp', 'WhatsApp'), ('staff', 'Staff')], default='app', max_length=20, verbose_name='Origen')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Teléfono del cliente')),
                ('party_size', models.PositiveSmallIntegerField(verbose_name='Personas')),
                ('floor', models.PositiveSmallIntegerField(default=2, help_text='La Sala VIP siempre es piso 3', verbose_name='Piso')),
                ('tables_needed', models.PositiveSmallIntegerField(default=1, help_text='Calculado a partir del tamaño del grupo; la sala no usa este campo', verbose_name='Mesas que ocupa')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de llegada / inicio de turno')),
                ('end_time', models.TimeField(verbose_name='Fin estimado / fin de turno')),
                ('vip_slot', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Tarde'), (2, 'Noche')], null=True, verbose_name='Turno de la sala')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Anticipo')),
                ('min_consumption', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Consumo mínimo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas del cliente')),
                ('staff_notes', models.TextField(blank=True, default='', verbose_name='Notas del staff')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Estado cambiado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Estado cambiado por')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='orders.table', verbose_name='Mesa asignada')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Cliente (cuenta)')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['date', 'start_time', 'id'],
                'indexes': [models.Index(fields=['date', 'floor'], name='reservation_date_ad3ee2_idx'), models.Index(fields=['status'], name='reservation_status_f1a03a_idx')],
            },
        ),
    ]
