# Generated by Django 6.0 on 2026-05-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, help_text='Identificador único de la cuenta de Google', max_length=255, null=True, unique=True, verbose_name='Google ID (sub)'),
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=20, verbose_name='Proveedor de autenticación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('employee', 'Empleado'), ('customer', 'Cliente')], default='employee', max_length=20, verbose_name='Rol'),
        ),
    ]
