# Generated by Django 6.0 on 2026-06-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_url_user_google_sub_user_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_opt_out',
            field=models.BooleanField(default=False, help_text='Si está activo, el usuario se dio de baja de los correos de la Polla.', verbose_name='No recibir correos'),
        ),
    ]
