# Generated by Django 6.0 on 2026-09-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_unaccent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_opt_out',
            field=models.BooleanField(default=False, help_text='Si está activo, el usuario se dio de baja de los correos de Frostbyte.', verbose_name='No recibir correos'),
        ),
    ]
