# Generated by Django 6.0 on 2026-03-10 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostorGameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_rounds', models.PositiveIntegerField(verbose_name='Total de rondas')),
                ('impostor_count', models.PositiveIntegerField(default=1, verbose_name='Cantidad de impostores')),
                ('hint_enabled', models.BooleanField(default=False, verbose_name='Pista habilitada')),
                ('trap_word_enabled', models.BooleanField(default=True, verbose_name='Palabra trampa habilitada')),
                ('spy_enabled', models.BooleanField(default=False, verbose_name='Rol espía habilitado')),
                ('turn_timer_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Timer por turno (segundos)')),
                ('ai_words_used', models.BooleanField(default=False, verbose_name='Palabras IA usadas')),
                ('status', models.CharField(choices=[('in_progress', 'En progreso'), ('completed', 'Completada'), ('abandoned', 'Abandonada')], default='in_progress', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada')),
            ],
            options={
                'verbose_name': 'Sesión de Impostor',
                'verbose_name_plural': 'Sesiones de Impostor',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único de la categoría (ej: deportes)', unique=True, verbose_name='Slug')),
                ('name', models.CharField(help_text='Nombre para mostrar (ej: Deportes)', max_length=100, verbose_name='Nombre')),
                ('icon', models.CharField(help_text='Nombre del icono Lucide (ej: Trophy)', max_length=50, verbose_name='Icono')),
                ('has_images', models.BooleanField(default=False, verbose_name='Tiene imágenes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de palabras',
                'verbose_name_plural': 'Categorías de palabras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImpostorPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('color', models.CharField(help_text='Color elegido por el jugador (ej: #ff00d4)', max_length=20, verbose_name='Color')),
                ('total_score', models.IntegerField(default=0, verbose_name='Puntuación total')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Se unió')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='impostor.impostorgamesession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Jugador Impostor',
                'verbose_name_plural': 'Jugadores Impostor',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpostorRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Número de ronda')),
                ('category_slug', models.CharField(max_length=50, verbose_name='Categoría')),
                ('word', models.CharField(max_length=100, verbose_name='Palabra real')),
                ('trap_word', models.CharField(blank=True, default='', max_length=100, verbose_name='Palabra trampa')),
                ('impostor_caught', models.BooleanField(default=False, verbose_name='Impostor descubierto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='impostor.impostorgamesession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Ronda Impostor',
                'verbose_name_plural': 'Rondas Impostor',
                'ordering': ['round_number'],
                'unique_together': {('session', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='ImpostorRoundPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('normal', 'Normal'), ('impostor', 'Impostor'), ('spy', 'Espía')], default='normal', max_length=10, verbose_name='Rol')),
                ('votes_received', models.PositiveIntegerField(default=0, verbose_name='Votos recibidos')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Puntos ganados')),
                ('guessed_word', models.CharField(blank=True, default='', help_text='Si el impostor intentó adivinar la palabra real', max_length=100, verbose_name='Palabra adivinada')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='impostor.impostorplayer', verbose_name='Jugador')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_results', to='impostor.impostorround', verbose_name='Ronda')),
                ('voted_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes_received_set', to='impostor.impostorplayer', verbose_name='Votó por')),
            ],
            options={
                'verbose_name': 'Resultado jugador por ronda',
                'verbose_name_plural': 'Resultados jugadores por ronda',
                'unique_together': {('round', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='La palabra real que ven los jugadores normales', max_length=100, verbose_name='Palabra')),
                ('trap_word', models.CharField(help_text='Palabra similar que ve el impostor (ej: si la real es Fútbol, la trampa es Tenis)', max_length=100, verbose_name='Palabra trampa')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL de imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='impostor.wordcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Palabra',
                'verbose_name_plural': 'Palabras',
                'ordering': ['word'],
                'unique_together': {('category', 'word')},
            },
        ),
    ]
