# Generated by Django 6.0 on 2025-12-31 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_alter_order_table_number_allow_zero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(help_text='Número de mesa (0=Barra, 1-5=Mesas)', unique=True, verbose_name='Número de mesa')),
                ('qr_code', models.CharField(help_text='Código único del QR físico de la mesa', max_length=100, unique=True, verbose_name='Código QR')),
                ('is_active', models.BooleanField(default=True, help_text='Si la mesa está disponible para juegos', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(help_text='Código único para compartir la sala', max_length=8, unique=True, verbose_name='Código de sala')),
                ('room_link', models.CharField(help_text='Link único para acceder a la sala', max_length=200, unique=True, verbose_name='Link de sala')),
                ('total_rounds', models.PositiveIntegerField(default=3, help_text='Número de rondas configuradas (1, 3 o 5)', verbose_name='Total de rondas')),
                ('current_round', models.PositiveIntegerField(default=0, help_text='Ronda que se está jugando actualmente (0 = no iniciado)', verbose_name='Ronda actual')),
                ('status', models.CharField(choices=[('waiting', 'Esperando jugadores'), ('configuring', 'Configurando juego'), ('playing', 'Jugando'), ('finished', 'Finalizada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='waiting', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciada')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada')),
                ('expires_at', models.DateTimeField(help_text='Momento en que la sala expira por inactividad', verbose_name='Expira')),
                ('order', models.ForeignKey(help_text='Pedido activo asociado a esta sala', on_delete=django.db.models.deletion.CASCADE, related_name='game_rooms', to='orders.order', verbose_name='Pedido')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rooms', to='games.table', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Sala de juego',
                'verbose_name_plural': 'Salas de juego',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(help_text='Nombre que el jugador elige para jugar', max_length=50, verbose_name='Nombre del jugador')),
                ('player_device_id', models.CharField(help_text='Identificador único del dispositivo del jugador', max_length=200, verbose_name='ID del dispositivo')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.gameroom', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['joined_at'],
                'unique_together': {('room', 'player_device_id')},
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Número de ronda')),
                ('signal_delay_ms', models.PositiveIntegerField(help_text='Tiempo en milisegundos desde el inicio hasta la señal visual', verbose_name='Delay de señal (ms)')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finalizada')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.gameroom', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Ronda',
                'verbose_name_plural': 'Rondas',
                'ordering': ['round_number'],
                'unique_together': {('room', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='GameRoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_time_ms', models.PositiveIntegerField(blank=True, help_text='Tiempo desde la señal visual hasta el toque en milisegundos', null=True, verbose_name='Tiempo de reacción (ms)')),
                ('tapped_at', models.DateTimeField(blank=True, help_text='Momento exacto en que el jugador tocó la pantalla', null=True, verbose_name='Tocado')),
                ('is_disqualified', models.BooleanField(default=False, help_text='True si tocó antes de la señal (anticipación)', verbose_name='Descalificado')),
                ('did_not_tap', models.BooleanField(default=False, help_text='True si no tocó la pantalla en esta ronda', verbose_name='No tocó')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='games.gameparticipant', verbose_name='Participante')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='games.gameround', verbose_name='Ronda')),
            ],
            options={
                'verbose_name': 'Resultado de ronda',
                'verbose_name_plural': 'Resultados de ronda',
                'ordering': ['reaction_time_ms'],
                'unique_together': {('round', 'participant')},
            },
        ),
    ]
