# Generated by Django 6.0 on 2025-12-31 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='game_type',
            field=models.CharField(choices=[('chill', 'Chill (sin apuestas)')], default='chill', help_text='CHILL = sin apuestas, WAGER = con apuestas (futuro)', max_length=20, verbose_name='Tipo de juego'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='wager_product',
            field=models.ForeignKey(blank=True, help_text='Producto que se apuesta (solo para juegos con apuestas, NULL para CHILL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_room_wagers', to='products.productvariant', verbose_name='Producto de apuesta'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='wager_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad del producto apostado (solo para juegos con apuestas)', null=True, verbose_name='Cantidad de apuesta'),
        ),
    ]
