# Generated by Django 6.0 on 2025-12-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_add_game_type_and_wager_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroundresult',
            name='is_loser',
            field=models.BooleanField(default=False, help_text='True si este participante perdió la ronda/juego (para juegos con apuestas, futuro)', verbose_name='Perdedor'),
        ),
    ]
