# Generated by Django 6.0 on 2026-01-17 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_add_is_loser_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(help_text='Nombre que el jugador usó en este juego', max_length=50, verbose_name='Nombre del jugador')),
                ('player_device_id', models.CharField(db_index=True, help_text='Identificador único del dispositivo del jugador', max_length=200, verbose_name='ID del dispositivo')),
                ('total_rounds', models.PositiveIntegerField(help_text='Número de rondas que se jugaron en este juego', verbose_name='Total de rondas')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Momento en que se completó el juego', verbose_name='Fecha de registro')),
                ('game_finished_at', models.DateTimeField(help_text='Momento en que el juego terminó', verbose_name='Juego finalizado')),
                ('room', models.ForeignKey(help_text='Sala de juego que se completó', on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='games.gameroom', verbose_name='Sala de juego')),
                ('table', models.ForeignKey(help_text='Mesa donde se jugó', on_delete=django.db.models.deletion.CASCADE, related_name='game_usages', to='games.table', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Registro de uso de juego',
                'verbose_name_plural': 'Registros de uso de juegos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['player_device_id', '-created_at'], name='games_gameu_player__f15d55_idx')],
            },
        ),
    ]
