# Generated by Django 6.0 on 2026-07-01 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_add_game_usage_model'),
        ('orders', '0015_backfill_order_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Pedido asociado (opcional; las salas libres no dependen de un pedido)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_rooms', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Mesa asociada (opcional; las salas libres no tienen mesa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_rooms', to='games.table', verbose_name='Mesa'),
        ),
        migrations.AlterField(
            model_name='gameusage',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Mesa donde se jugó (opcional para salas libres)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_usages', to='games.table', verbose_name='Mesa'),
        ),
    ]
