services:
  db:
    image: ankane/pgvector
    container_name: frostbyte-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: frostbyte
      POSTGRES_PASSWORD: frostbyte
      POSTGRES_DB: frostbyte
    ports:
      - "5433:5432"
    volumes:
      - db-frostbyte-data:/var/lib/postgresql/data

volumes:
  db-frostbyte-data:
