# Generated by Django 6.0 on 2026-02-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommenderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('mood', 'Estado de ánimo'), ('quiz', 'Quiz rápido')], max_length=10, verbose_name='Tipo de consulta')),
                ('input_data', models.JSONField(verbose_name='Datos ingresados')),
                ('recommended_product_name', models.CharField(max_length=200, verbose_name='Producto recomendado')),
                ('recommended_product_slug', models.CharField(blank=True, max_length=200, verbose_name='Slug del producto')),
                ('ai_reason', models.TextField(blank=True, verbose_name='Razón de la IA')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Registro de recomendación',
                'verbose_name_plural': 'Registros de recomendaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
