# Generated by Django 6.0 on 2026-09-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivational', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI')], max_length=20, verbose_name='Proveedor')),
                ('status', models.CharField(choices=[('ok', 'Generada'), ('failed', 'Fallida')], max_length=20, verbose_name='Resultado')),
                ('model_name', models.CharField(blank=True, max_length=80, verbose_name='Modelo')),
                ('was_fallback', models.BooleanField(default=False, verbose_name='Entró como respaldo')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Duración (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Tarjeta generada',
                'verbose_name_plural': 'Tarjetas generadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
