# Generated by Django 6.0 on 2026-05-05 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivational', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=60, verbose_name='De parte de')),
                ('mother_name', models.CharField(blank=True, max_length=60, verbose_name='Para mamá')),
                ('message', models.CharField(max_length=240, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Mensaje de amor')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Aprobada')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Dedicatoria Día de la Madre',
                'verbose_name_plural': 'Dedicatorias Día de la Madre',
                'ordering': ['-created_at'],
            },
        ),
    ]
