# Generated by Django 6.0 on 2026-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivational', '0002_motherdedication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MothersDayCardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('photo_uploaded', 'Foto cargada'), ('phrase_generated', 'Frase generada'), ('image_generated', 'Tarjeta generada'), ('downloaded', 'Tarjeta descargada'), ('shared', 'Tarjeta compartida')], max_length=20, verbose_name='Tipo de evento')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Evento tarjeta Día de la Madre',
                'verbose_name_plural': 'Eventos tarjeta Día de la Madre',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='motivationa_event_t_e5acc2_idx')],
            },
        ),
    ]
