# Generated by Django 6.0 on 2025-12-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200, verbose_name='Nombre de la canción')),
                ('artist_name', models.CharField(max_length=200, verbose_name='Nombre del artista')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('playing', 'Reproduciendo'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Información adicional sobre la solicitud', verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('played_at', models.DateTimeField(blank=True, null=True, verbose_name='Reproducido')),
            ],
            options={
                'verbose_name': 'Solicitud de canción',
                'verbose_name_plural': 'Solicitudes de canciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
