# Generated by Django 6.0 on 2026-03-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('scope', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token de Spotify',
                'verbose_name_plural': 'Tokens de Spotify',
            },
        ),
        migrations.AddField(
            model_name='songrequest',
            name='spotify_track_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración en ms'),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='spotify_track_image',
            field=models.URLField(blank=True, verbose_name='Imagen del track'),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='spotify_track_uri',
            field=models.CharField(blank=True, help_text='URI del track en Spotify (spotify:track:xxx)', max_length=100, verbose_name='URI de Spotify'),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('queued', 'En cola'), ('playing', 'Reproduciendo'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('failed', 'Fallida')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
