# Generated by Django 6.0 on 2026-04-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_spotifytoken_songrequest_spotify_track_duration_ms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('spotify', 'Spotify'), ('youtube', 'YouTube')], default='youtube', max_length=20, verbose_name='Fuente de musica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de musica',
                'verbose_name_plural': 'Configuracion de musica',
            },
        ),
    ]
