# Generated by Django 6.0 on 2026-07-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_musicsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='floor',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Piso 2'), (3, 'Piso 3')], default=2, help_text='Piso donde sonará la canción (cada piso tiene su Spotify)', verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='spotifytoken',
            name='floor',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Piso 2'), (3, 'Piso 3')], default=2, unique=True, verbose_name='Piso'),
        ),
    ]
