# Generated by Django 6.0 on 2026-09-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_songrequest_floor_spotifytoken_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_key', models.CharField(help_text='Nombre normalizado (sin tildes ni mayúsculas) usado para cruzar con las canciones', max_length=200, unique=True, verbose_name='Clave del artista')),
                ('artist_name', models.CharField(help_text='Nombre tal como lo devuelve Spotify', max_length=200, verbose_name='Artista')),
                ('genre', models.CharField(choices=[('corridos', 'Corridos y regional mexicano'), ('popular', 'Popular y despecho'), ('ranchera', 'Ranchera y mariachi'), ('vallenato', 'Vallenato'), ('salsa', 'Salsa y son'), ('cumbia', 'Cumbia y andina'), ('reggaeton', 'Reggaetón y urbano'), ('bachata', 'Bachata y merengue'), ('balada', 'Balada y romántica'), ('rock', 'Rock y metal'), ('pop', 'Pop'), ('rap', 'Rap y hip hop'), ('electronica', 'Electrónica'), ('reggae', 'Reggae y dancehall'), ('otros', 'Otros')], max_length=30, verbose_name='Género')),
                ('source', models.CharField(choices=[('ai', 'Clasificado por IA'), ('manual', 'Corregido a mano')], default='ai', max_length=10, verbose_name='Origen')),
                ('model_used', models.CharField(blank=True, help_text='Modelo de lenguaje que hizo la clasificación', max_length=60, verbose_name='Modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Género de artista',
                'verbose_name_plural': 'Géneros de artistas',
                'ordering': ['artist_name'],
                'indexes': [models.Index(fields=['genre'], name='music_artis_genre_8f8a96_idx')],
            },
        ),
    ]
