# Generated by Django 6.0 on 2026-04-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titulo del video')),
                ('channel_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del canal')),
                ('video_id', models.CharField(help_text='El ID del video (ej: dQw4w9WgXcQ)', max_length=20, verbose_name='ID del video de YouTube')),
                ('thumbnail', models.URLField(blank=True, verbose_name='Thumbnail del video')),
                ('duration', models.CharField(blank=True, help_text='Duracion en formato ISO 8601 (ej: PT4M30S)', max_length=20, verbose_name='Duracion')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('queued', 'En cola'), ('playing', 'Reproduciendo'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('played_at', models.DateTimeField(blank=True, null=True, verbose_name='Reproducido')),
            ],
            options={
                'verbose_name': 'Solicitud de video',
                'verbose_name_plural': 'Solicitudes de videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
