# Generated by Django 6.0 on 2026-04-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('thumbnail', models.URLField(blank=True)),
                ('is_mix', models.BooleanField(default=False, help_text='True si viene del Mix automatico')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado TV YouTube',
                'verbose_name_plural': 'Estado TV YouTube',
            },
        ),
    ]
