# Generated by Django 6.0 on 2026-07-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(help_text='Header X-Idempotency-Key de Kapso (o hash del body si no vino)', max_length=128, unique=True, verbose_name='Clave de idempotencia')),
                ('phone_number_id', models.CharField(blank=True, max_length=64, verbose_name='Número destino')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono del cliente')),
                ('event_type', models.CharField(blank=True, max_length=64, verbose_name='Tipo de evento')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processed', 'Procesado'), ('ignored', 'Ignorado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibido')),
            ],
            options={
                'verbose_name': 'Evento de webhook',
                'verbose_name_plural': 'Eventos de webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Solo dígitos, con indicativo de país (ej. 573001234567)', max_length=30, unique=True, verbose_name='Teléfono')),
                ('wa_user_id', models.CharField(blank=True, db_index=True, help_text='business_scoped_user_id de Meta; estable aunque el número no venga', max_length=64, verbose_name='ID de usuario de WhatsApp')),
                ('profile_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre de perfil')),
                ('customer_name', models.CharField(blank=True, help_text='Nombre que el cliente confirmó para sus pedidos', max_length=200, verbose_name='Nombre confirmado')),
                ('default_address', models.CharField(blank=True, max_length=300, verbose_name='Dirección habitual')),
                ('default_reference', models.CharField(blank=True, max_length=300, verbose_name='Referencia habitual')),
                ('notes', models.TextField(blank=True, help_text='Preferencias de largo plazo aprendidas por el agente', verbose_name='Preferencias')),
                ('last_phone_number_id', models.CharField(blank=True, help_text='phone_number_id por el que escribió la última vez; se usa para notificarle', max_length=64, verbose_name='Último número Kapso')),
                ('human_handoff', models.BooleanField(default=False, help_text='Si está activo, el agente NO responde a este contacto hasta desactivarlo', verbose_name='Atendido por humano')),
                ('is_blocked', models.BooleanField(default=False, help_text='El agente ignora por completo los mensajes de este contacto', verbose_name='Bloqueado')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Último mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Contacto de WhatsApp',
                'verbose_name_plural': 'Contactos de WhatsApp',
                'ordering': ['-last_message_at'],
            },
        ),
    ]
