# Generated by Django 6.0 on 2026-07-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(max_length=128, unique=True, verbose_name='ID de mensaje')),
                ('to_phone', models.CharField(blank=True, max_length=30, verbose_name='Destinatario')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Enviado')),
            ],
            options={
                'verbose_name': 'Mensaje enviado por el sistema',
                'verbose_name_plural': 'Mensajes enviados por el sistema',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='human_until',
            field=models.DateTimeField(blank=True, help_text='Mientras esta hora esté en el futuro el agente no responde: un humano del equipo intervino en el chat. Se renueva con cada mensaje del humano', null=True, verbose_name='Pausa humana hasta'),
        ),
    ]
