# Generated by Django 6.0 on 2026-07-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_sentmessage_whatsappcontact_human_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='last_location_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ubicación compartida el'),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='last_location_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Última ubicación de WhatsApp que compartió el cliente. La lee crear_pedido: el agente nunca maneja coordenadas (no puede inventarlas)', max_digits=10, null=True, verbose_name='Última ubicación (lat)'),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='last_location_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Última ubicación (lng)'),
        ),
    ]
