# Generated by Django 6.0 on 2026-08-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_whatsappcontact_last_location_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(max_length=128, unique=True, verbose_name='ID de mensaje')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono del cliente')),
                ('direction', models.CharField(choices=[('inbound', 'Del cliente'), ('outbound', 'Del negocio')], default='inbound', max_length=10, verbose_name='Dirección')),
                ('body', models.TextField(blank=True, verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Texto de mensaje (citas)',
                'verbose_name_plural': 'Textos de mensajes (citas)',
                'ordering': ['-created_at'],
            },
        ),
    ]
