# Generated by Django 6.0 on 2026-08-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mensaje de la conversación', 'verbose_name_plural': 'Mensajes de las conversaciones'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='author',
            field=models.CharField(choices=[('customer', 'Cliente'), ('agent', 'Agente IA'), ('human', 'Persona del equipo')], db_index=True, default='customer', help_text='Distingue lo que respondió el agente de lo que escribió una persona del equipo.', max_length=10, verbose_name='Quién lo escribió'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['phone', 'created_at'], name='whatsapp_ch_phone_f40da6_idx'),
        ),
    ]
