# Generated by Django 6.0 on 2026-08-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_backfill_chatmessage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='username',
            field=models.CharField(blank=True, help_text='Nombre de usuario de WhatsApp, si el cliente tiene; puede cambiar', max_length=64, verbose_name='Usuario de WhatsApp'),
        ),
        migrations.AlterField(
            model_name='sentmessage',
            name='to_phone',
            field=models.CharField(blank=True, max_length=160, verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=160, verbose_name='Teléfono del cliente'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='phone',
            field=models.CharField(help_text='Solo dígitos con indicativo de país (ej. 573001234567) o, si el cliente oculta su número, su BSUID de Meta (ej. CO.2430294670795328)', max_length=160, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='wa_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='business_scoped_user_id de Meta; estable aunque el número no venga', max_length=160, verbose_name='ID de usuario de WhatsApp'),
        ),
    ]
