# Generated by Django 6.0 on 2026-08-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_whatsappcontact_username_bsuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Número que dio el cliente para llamarlo cuando WhatsApp no muestra el suyo (contactos identificados por BSUID)', max_length=30, verbose_name='Celular de contacto'),
        ),
    ]
