# Generated by Django 6.0 on 2026-09-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_whatsappcontact_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(default='Frosty', help_text='Con este nombre se presenta ante el cliente.', max_length=40, verbose_name='Nombre del agente')),
                ('tone', models.TextField(blank=True, help_text="Instrucciones extra sobre CÓMO habla (no sobre qué hace). Se añaden al final del prompt, así que mandan sobre el estilo por defecto. Ej.: 'Trata al cliente de usted' o 'sin emojis'. Vacío = el tono por defecto.", verbose_name='Tono y personalidad')),
                ('stickers_enabled', models.BooleanField(default=True, help_text='Si se apaga, el agente no ve el banco de stickers y nunca manda uno.', verbose_name='Puede mandar stickers')),
                ('reactions_enabled', models.BooleanField(default=True, help_text='Reacciones de WhatsApp sobre el mensaje del cliente (❤️, 😂, 👀).', verbose_name='Puede reaccionar con emoji')),
                ('product_photos_enabled', models.BooleanField(default=True, help_text='Manda la foto real del producto cuando el cliente pregunta cómo es.', verbose_name='Puede mandar fotos de productos')),
                ('quick_replies_enabled', models.BooleanField(default=True, help_text='Botones de respuesta rápida (máx. 3) para confirmar el pedido o elegir pago.', verbose_name='Puede mandar botones')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración del agente',
                'verbose_name_plural': 'Configuración del agente',
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Corto y en minúsculas, como lo pediría alguien: 'granizado feliz', 'pulgar arriba'.", max_length=60, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(help_text="Lo único que el agente lee para elegirlo. Describe el MOMENTO, no el dibujo: 'para celebrar que el pedido quedó listo', no 'un vaso azul con ojos'.", max_length=200, verbose_name='Cuándo usarlo')),
                ('data', models.BinaryField(verbose_name='Archivo WebP')),
                ('byte_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('is_animated', models.BooleanField(default=False, verbose_name='Animado')),
                ('is_active', models.BooleanField(default=True, help_text='Los inactivos no se le muestran al agente.', verbose_name='Activo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Veces enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Sticker',
                'verbose_name_plural': 'Stickers',
                'ordering': ['display_order', 'label'],
            },
        ),
    ]
