# Generated by Django 6.0 on 2026-09-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_agentsettings_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='owner_phones',
            field=models.CharField(blank=True, default='573164277879', help_text='Separados por coma, con indicativo (573001234567). Desde estos números el agente reconoce al dueño: lo trata distinto y le deja gestionar sus stickers y su tono por chat. Sigue tomándole pedidos de verdad.', max_length=200, verbose_name='Números del dueño'),
        ),
        migrations.CreateModel(
            name='StickerDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Imagen'), ('sticker', 'Sticker'), ('video', 'Video')], max_length=10, verbose_name='Tipo')),
                ('data', models.BinaryField(verbose_name='Archivo original')),
                ('mime', models.CharField(blank=True, max_length=80, verbose_name='Tipo MIME')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Recibido')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sticker_draft', to='whatsapp.whatsappcontact', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Archivo pendiente de volverse sticker',
                'verbose_name_plural': 'Archivos pendientes de volverse sticker',
            },
        ),
    ]
