# Generated by Django 6.0 on 2026-09-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_agentsettings_owner_phones_stickerdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='tone_preset',
            field=models.CharField(choices=[('parcero', 'Parcero'), ('cercano', 'Cercano'), ('serio', 'Serio'), ('directo', 'Directo')], default='parcero', help_text='Con cuál de las personalidades habla. Reemplaza el bloque de QUIÉN ERES del prompt: no se suma al de por defecto, lo sustituye.', max_length=20, verbose_name='Tono'),
        ),
        migrations.AlterField(
            model_name='agentsettings',
            name='quick_replies_enabled',
            field=models.BooleanField(default=True, help_text='Botones de respuesta rápida (máx. 3) para confirmar el pedido. El método de pago NUNCA se pregunta con botones.', verbose_name='Puede mandar botones'),
        ),
        migrations.AlterField(
            model_name='agentsettings',
            name='tone',
            field=models.TextField(blank=True, help_text="Instrucciones extra sobre CÓMO habla (no sobre qué hace). Se añaden al final del prompt, así que mandan sobre el tono elegido. Ej.: 'Trata al cliente de usted' o 'sin emojis'. Vacío = solo el tono elegido.", verbose_name='Ajustes de tono'),
        ),
    ]
