# Generated by Django 6.0 on 2026-09-03 20:15

from django.db import migrations, models

from apps.whatsapp.tones import SEED_TONES


def sembrar_tonos(apps, schema_editor):
    """Mete en la tabla los cuatro tonos que hasta ahora vivían en el código.

    Se leen de `tones.SEED_TONES` en vez de copiarlos aquí a propósito: ese
    módulo sigue siendo la versión de fábrica —la que devuelve el botón de
    restaurar— y tenerlos en dos sitios los dejaría distintos a la primera
    corrección de redacción. Es `get_or_create`, así que volver a correrla no
    pisa lo que el dueño haya editado.
    """
    AgentTone = apps.get_model("whatsapp", "AgentTone")
    for orden, tone in enumerate(SEED_TONES):
        AgentTone.objects.get_or_create(
            key=tone["key"],
            defaults={**tone, "is_builtin": True, "display_order": orden},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0011_agentsettings_tone_preset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Identificador estable; se genera del nombre y no cambia después.', max_length=30, unique=True, verbose_name='Clave')),
                ('name', models.CharField(help_text="Como se ve en el panel al elegirlo: 'Parcero', 'Serio'.", max_length=40, verbose_name='Nombre')),
                ('description', models.CharField(help_text='Una línea que resuma el tono para quien elige. No la lee el agente.', max_length=200, verbose_name='De qué va')),
                ('sample', models.CharField(blank=True, help_text='Cómo sonaría un saludo suyo. Tampoco la lee el agente: es para el panel.', max_length=200, verbose_name='Frase de ejemplo')),
                ('persona', models.TextField(help_text="Esto SÍ lo lee el agente: es el bloque QUIÉN ERES del prompt. Escríbelo en segunda persona ('eres…', 'tuteas…') y di también qué hacer cuando el cliente está molesto.", verbose_name='Personalidad')),
                ('is_builtin', models.BooleanField(default=False, editable=False, help_text='Los que vinieron con el sistema; se pueden devolver a su texto original.', verbose_name='De fábrica')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Tono del agente',
                'verbose_name_plural': 'Tonos del agente',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='agentsettings',
            name='tone_preset',
            field=models.CharField(default='parcero', help_text='Clave del tono con el que habla (ver Tonos del agente). Reemplaza el bloque de QUIÉN ERES del prompt: no se suma al de por defecto, lo sustituye.', max_length=30, verbose_name='Tono'),
        ),
        migrations.RunPython(sembrar_tonos, migrations.RunPython.noop),
    ]
