# Generated by Django 6.0 on 2026-09-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0012_agenttone_alter_agentsettings_tone_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='sticker_log',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Los últimos que el agente le mandó a este contacto, del más nuevo al más viejo. Es su memoria corta: sin ella repetiría el mismo sticker y lo mandaría en cada mensaje (ver mood.sticker_urge)', verbose_name='Stickers recientes'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='description',
            field=models.CharField(help_text="Lo único que el agente lee para elegirlo. Describe el MOMENTO o el ánimo, no el dibujo: 'para celebrar que el pedido quedó listo', no 'un vaso azul con ojos'. No es exclusivo: varios pueden servir para lo mismo, y cuantos más haya para un mismo ánimo menos se repite el agente.", max_length=200, verbose_name='Cuándo usarlo'),
        ),
    ]
