# Generated by Django 6.0 on 2026-09-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0013_whatsappcontact_sticker_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttone',
            name='sample',
            field=models.CharField(blank=True, help_text='Cómo sonaría un saludo suyo. Se ve en el panel y además se la damos al agente: una frase de muestra le calibra el registro mejor que un párrafo describiéndoselo.', max_length=200, verbose_name='Frase de ejemplo'),
        ),
    ]
