# Generated by Django 6.0 on 2026-09-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0014_alter_agenttone_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='banned_words',
            field=models.CharField(blank=True, help_text='Separadas por coma (ej.: parce, pana). Estas NO dependen de que el agente haga caso: se le quitan al mensaje antes de enviarlo, aunque el tono elegido las use como ejemplo. Palabras sueltas, no frases.', max_length=300, verbose_name='Palabras que nunca debe decir'),
        ),
    ]
