# Generated by Django 6.0 on 2026-09-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0016_tono_sin_jerga_paisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='last_location_label',
            field=models.CharField(blank=True, help_text="Nombre y dirección que WhatsApp mandó con la ubicación (ej. 'Mundo Fotográfico · Cl. 19 #10-7'). Sirve para que el agente le pregunte al cliente que vuelve si es al mismo sitio, en vez de pedirle otra vez que comparta la ubicación", max_length=200, verbose_name='Cómo se llama esa ubicación'),
        ),
    ]
