# Generated by Django 6.0 on 2026-09-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0017_whatsappcontact_last_location_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='rescued_wamid',
            field=models.CharField(blank=True, editable=False, help_text='El mensaje del cliente que el vigía ya intentó contestar (ver watchdog.py). Sin esto, un turno que decide callarse se volvería a intentar cada minuto', max_length=128, verbose_name='Último mensaje rescatado'),
        ),
    ]
