# Generated by Django 6.0 on 2026-09-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0018_whatsappcontact_rescued_wamid'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='delivery_missed_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='La última vez que este contacto escribió con los domicilios apagados. Cuando vuelven a prenderse, el vigía mira la conversación y le avisa si se quedó sin su pedido por eso (ver domicilios.py). Se borra en cuanto hace un pedido', null=True, verbose_name='Se quedó sin domicilio el'),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='delivery_notified_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Cuándo se le avisó que los domicilios volvieron. Sin esto, cada barrido volvería a intentarlo mientras siguieran activos', null=True, verbose_name='Avisado de los domicilios el'),
        ),
    ]
