# Generated by Django 6.0 on 2026-06-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre del negocio')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('floor', models.PositiveSmallIntegerField(blank=True, help_text='Piso físico del negocio (ej. 2 = bebidas, 3 = comida).', null=True, verbose_name='Piso')),
                ('color', models.CharField(blank=True, default='', help_text='Color para la UI (ej: blue, orange).', max_length=20, verbose_name='Color de marca')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
