# Generated by Django 6.0 on 2026-01-18 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, help_text='Opcional - Nombre del cliente', max_length=100, verbose_name='Nombre del cliente')),
                ('comment', models.TextField(help_text='El mensaje o comentario del cliente', verbose_name='Comentario')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Calificacion del 1 al 5 estrellas (opcional)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificacion')),
                ('feedback_type', models.CharField(choices=[('suggestion', 'Sugerencia'), ('complaint', 'Queja'), ('compliment', 'Felicitacion'), ('question', 'Pregunta'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de feedback')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('responded', 'Respondido'), ('archived', 'Archivado')], default='pending', max_length=20, verbose_name='Estado')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas internas sobre este feedback', verbose_name='Notas del administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
