# Generated by Django 6.0 on 2025-12-23 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock actual')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, help_text='Nivel de stock para alertar reabastecimiento', max_digits=10, verbose_name='Stock mínimo')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, help_text='Costo en COP por unidad de medida', max_digits=10, verbose_name='Costo por unidad')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='inventory.unitofmeasure', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Materia prima',
                'verbose_name_plural': 'Materias primas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Cantidad necesaria por unidad de producto', max_digits=10, verbose_name='Cantidad')),
                ('notes', models.CharField(blank=True, help_text='Instrucciones especiales', max_length=200, verbose_name='Notas')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='products.productvariant', verbose_name='Variante de producto')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='inventory.rawmaterial', verbose_name='Materia prima')),
            ],
            options={
                'verbose_name': 'Ingrediente de receta',
                'verbose_name_plural': 'Ingredientes de receta',
                'ordering': ['product_variant', 'raw_material__name'],
                'unique_together': {('product_variant', 'raw_material')},
            },
        ),
    ]
