# Generated by Django 6.0 on 2025-12-23 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número de orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('purchased', 'Comprado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total estimado')),
                ('actual_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total real')),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad necesaria')),
                ('quantity_purchased', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad comprada')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario estimado')),
                ('actual_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio unitario real')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='Comprado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder', verbose_name='Orden de compra')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.rawmaterial', verbose_name='Materia prima')),
            ],
            options={
                'verbose_name': 'Item de orden de compra',
                'verbose_name_plural': 'Items de orden de compra',
                'ordering': ['raw_material__name'],
            },
        ),
    ]
