"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta
import os
import sys
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file for local development
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY', 'django-insecure-4y%)(zgqyk#duz4az0=ts&k23tkn4e4q+^hmu=1*riaes2^k=m')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['*']

DATABASE_URL = os.getenv('DATABASE_URL')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',
    # Local apps - accounts first (custom user model)
    'apps.accounts',
    'apps.business',
    'apps.products',
    'apps.inventory',
    'apps.orders',
    'apps.music',
    'apps.games',
    'apps.motivational',
    'apps.feedback',
    'apps.expenses',
    'apps.analytics',
    'apps.ai_generator',
    'apps.impostor',
    'apps.recetarios',
    'apps.youtube',
    'apps.polla',  # solo modelos: conserva los datos del Mundial 2026
    'apps.whatsapp',
    'apps.reservations',
]

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=0)
}

DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'

CONN_HEALTH_CHECKS = True

# Techos de espera contra la base. Sin ellos, una consulta que se traba deja
# el request colgado hasta que daphne lo mata ("took too long to shut down"),
# el cajero ve la app congelada y no hay ningun error que mirar. Con techo,
# la operacion falla rapido, con excepcion, y el front puede reintentar.
#
#   lock_timeout      un pedido bloqueado por otra transaccion no espera mas
#                     que esto (marcar pagado dos veces a la vez, por ejemplo)
#   statement_timeout tope duro por consulta
#   idle_in_transaction_session_timeout
#                     una transaccion abierta y olvidada suelta sus locks sola
#
# Solo aplican al proceso web: los comandos de manage.py (migrate, seeds, el
# los seeds) hacen consultas legitimamente largas y quedan exentos.
# Ojo: esto NO cubre un disco lento en el commit -el fsync del WAL no se puede
# interrumpir desde el cliente-, cubre esperas por lock y consultas pesadas.
_IS_MANAGEMENT_COMMAND = os.path.basename(sys.argv[0] or '') == 'manage.py'

DB_STATEMENT_TIMEOUT_MS = int(os.getenv('DB_STATEMENT_TIMEOUT_MS', '30000'))
DB_LOCK_TIMEOUT_MS = int(os.getenv('DB_LOCK_TIMEOUT_MS', '5000'))
DB_IDLE_TX_TIMEOUT_MS = int(os.getenv('DB_IDLE_TX_TIMEOUT_MS', '60000'))

# El techo para conectar es mas holgado en los comandos: 'migrate' corre al
# arrancar el contenedor, cuando la red privada de Railway todavia puede estar
# levantandose, y un deploy que falla por eso seria un error nuevo, nuestro.
DB_CONNECT_TIMEOUT = int(os.getenv(
    'DB_CONNECT_TIMEOUT', '20' if _IS_MANAGEMENT_COMMAND else '5'))

_db_options = DATABASES['default'].setdefault('OPTIONS', {})
_db_options.setdefault('connect_timeout', DB_CONNECT_TIMEOUT)

if not _IS_MANAGEMENT_COMMAND:
    _pg_flags = []
    if DB_STATEMENT_TIMEOUT_MS > 0:
        _pg_flags.append(f'-c statement_timeout={DB_STATEMENT_TIMEOUT_MS}')
    if DB_LOCK_TIMEOUT_MS > 0:
        _pg_flags.append(f'-c lock_timeout={DB_LOCK_TIMEOUT_MS}')
    if DB_IDLE_TX_TIMEOUT_MS > 0:
        _pg_flags.append(
            f'-c idle_in_transaction_session_timeout={DB_IDLE_TX_TIMEOUT_MS}')
    if _pg_flags:
        # Respetar lo que ya venga en la URL de conexion en vez de pisarlo.
        _existing = _db_options.get('options', '').strip()
        _db_options['options'] = ' '.join(
            ([_existing] if _existing else []) + _pg_flags)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (uploads: imágenes de IA, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.StandardResultsPagination',
    'PAGE_SIZE': 50,
}

# Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    # Ventana deslizante: con ROTATE_REFRESH_TOKENS, cada renovacion emite un
    # refresh token nuevo con 90 dias de vida desde ese momento. Mientras el
    # cliente entre al menos una vez cada 90 dias, la sesion no expira nunca.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Channels configuration
ASGI_APPLICATION = 'config.asgi.application'

# Channel layers (usando in-memory para desarrollo, Redis para producción)
REDIS_URL = os.getenv('REDIS_URL')

# Techos de espera contra Redis. Sin socket_timeout, una conexion TCP que
# quedo muerta (la red la corto en silencio) bloquea la lectura hasta que el
# kernel se rinde: minutos. Eso basta para colgar un request o un consumer.
REDIS_CONNECT_TIMEOUT = float(os.getenv('REDIS_CONNECT_TIMEOUT', '3'))
REDIS_SOCKET_TIMEOUT = float(os.getenv('REDIS_SOCKET_TIMEOUT', '5'))

# El channel layer necesita un techo MAS ALTO que el del cache, y no es un
# detalle: channels_redis recibe con BRPOP y espera brpop_timeout (5 s) en cada
# vuelta del bucle. Si el socket expira en esos mismos 5 s, revienta mientras el
# BRPOP todavia esta esperando, sin que pase nada malo. Con socket_timeout=5
# cada consumer moria con TimeoutError cada ~8 s (visto en produccion el
# 22/08 01:27). Tiene que quedar comodamente por encima de brpop_timeout.
REDIS_BRPOP_TIMEOUT = 5  # channels_redis.core.RedisChannelLayer.brpop_timeout
REDIS_CHANNEL_SOCKET_TIMEOUT = max(
    float(os.getenv('REDIS_CHANNEL_SOCKET_TIMEOUT', '15')),
    REDIS_BRPOP_TIMEOUT + 5,
)

if REDIS_URL:
    # Producción: usar Redis para channel layers
    # Railway provee REDIS_URL como redis://host:port o redis://:password@host:port
    # channels-redis acepta un dict por host: 'address' es la URL y el resto
    # son kwargs del pool de redis-py.
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [{
                    'address': REDIS_URL,
                    'socket_connect_timeout': REDIS_CONNECT_TIMEOUT,
                    'socket_timeout': REDIS_CHANNEL_SOCKET_TIMEOUT,
                    'socket_keepalive': True,
                    'health_check_interval': 30,
                }],
            },
        },
    }
else:
    # Desarrollo: usar in-memory channel layer
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# Cache configuration (Redis en prod, LocMem en dev)
# Usado principalmente para cachear respuestas de APIs externas (YouTube)
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'socket_connect_timeout': REDIS_CONNECT_TIMEOUT,
                'socket_timeout': REDIS_SOCKET_TIMEOUT,
                'health_check_interval': 30,
            },
        },
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'frostbyte-cache',
        },
    }

# Cloudflare R2 Configuration
R2_ACCOUNT_ID = os.getenv('R2_ACCOUNT_ID', '')
R2_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY', '')
R2_BUCKET_NAME = os.getenv('R2_BUCKET_NAME', '')
R2_PUBLIC_URL = os.getenv('R2_PUBLIC_URL', '')

# File Upload Settings
FILE_UPLOAD_MAX_SIZE = 5 * 1024 * 1024  # 5MB
ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'image/gif']

# OpenAI Configuration for Image Generation (GPT Image 1.5)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# Google Gemini Configuration for Image Generation
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')

# Google Sign-In (login de clientes con Google Identity Services)
# Mismo Client ID (OAuth 2.0 Web application) que usa el frontend.
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')

# Spotify Configuration
SPOTIFY_CLIENT_ID = os.getenv('SPOTIFY_CLIENT_ID', '')
SPOTIFY_CLIENT_SECRET = os.getenv('SPOTIFY_CLIENT_SECRET', '')
SPOTIFY_REDIRECT_URI = os.getenv('SPOTIFY_REDIRECT_URI', 'http://localhost:8000/api/v1/spotify/callback/')

# YouTube Configuration
YOUTUBE_API_KEY = os.getenv('YOUTUBE_API_KEY', '')
# Limite diario de unidades de cuota (free tier = 10000)
YOUTUBE_QUOTA_LIMIT = int(os.getenv('YOUTUBE_QUOTA_LIMIT', '10000'))

# Agente de pedidos por WhatsApp (Kapso + LangGraph)
# -------------------------------------------------------------------------
# Kapso recibe los mensajes de WhatsApp y nos los reenvía por webhook a
# /api/v1/whatsapp/webhook/. El agente (apps.whatsapp) responde vía la API de
# Kapso. KAPSO_PHONE_NUMBER_IDS lista los números propios (separados por coma)
# para ignorar eventos de números desconocidos.
KAPSO_API_KEY = os.getenv('KAPSO_API_KEY', '')
KAPSO_WEBHOOK_SECRET = os.getenv('KAPSO_WEBHOOK_SECRET', '')
KAPSO_PHONE_NUMBER_IDS = [
    s.strip() for s in os.getenv('KAPSO_PHONE_NUMBER_IDS', '').split(',') if s.strip()
]
# Interruptor general del agente (los webhooks se registran igual, sin responder)
WHATSAPP_AGENT_ENABLED = os.getenv('WHATSAPP_AGENT_ENABLED', 'True').lower() == 'true'
WHATSAPP_AGENT_MODEL = os.getenv('WHATSAPP_AGENT_MODEL', 'gpt-5.6-terra')
# Cuánto razona antes de responder (none|low|medium|high|xhigh|max). Solo lo
# usan los modelos de razonamiento (GPT-5 en adelante); 'low' es el equilibrio
# entre calidad y latencia que aguanta un chat de WhatsApp.
WHATSAPP_AGENT_REASONING_EFFORT = os.getenv('WHATSAPP_AGENT_REASONING_EFFORT', 'low')
# Leer lo que manda el cliente (audios e imágenes) es trabajo mecánico: va con
# modelos baratos aparte, y el modelo caro del agente queda solo para conversar
# y decidir. Un comprobante de pago sí se lee con visión buena: los montos.
WHATSAPP_VISION_MODEL = os.getenv('WHATSAPP_VISION_MODEL', 'gpt-5.6-luna')
WHATSAPP_TRANSCRIBE_MODEL = os.getenv('WHATSAPP_TRANSCRIBE_MODEL', 'gpt-4o-mini-transcribe')
# Datos de pago por transferencia que el agente comparte (Nequi/cuenta/etc.)
WHATSAPP_TRANSFER_INFO = os.getenv('WHATSAPP_TRANSFER_INFO', '')
# Número al que el agente remite cuando no sabe algo (contacto directo del local)
WHATSAPP_CONTACT_PHONE = os.getenv('WHATSAPP_CONTACT_PHONE', '3164277879')
# Minutos que el agente queda pausado tras cada mensaje que un humano del
# equipo envía al cliente (desde el inbox de Kapso o la app de WhatsApp)
WHATSAPP_HUMAN_PAUSE_MINUTES = int(os.getenv('WHATSAPP_HUMAN_PAUSE_MINUTES', '30'))
# Agrupado de mensajes seguidos: el agente espera este tanto desde el ÚLTIMO
# mensaje del cliente antes de responder (cada mensaje nuevo reinicia la
# cuenta), con un tope duro desde el primero para quien escribe sin parar.
# Se suma a la ventana de buffering de Kapso (recomendada: 2 s).
WHATSAPP_BATCH_WAIT_SECONDS = float(os.getenv('WHATSAPP_BATCH_WAIT_SECONDS', '10'))
WHATSAPP_BATCH_MAX_WAIT_SECONDS = float(
    os.getenv('WHATSAPP_BATCH_MAX_WAIT_SECONDS', '40')
)
BACKEND_PUBLIC_URL = os.getenv(
    'BACKEND_PUBLIC_URL', 'https://frostbyte-backend-production.up.railway.app'
)
SITE_URL = os.getenv('SITE_URL', 'https://frostbyte.com.co')

# Zona de cobertura de domicilios: el local (Cra. 8 #18-13, Cumbal). Debe
# coincidir con STORE_LOCATION del frontend (src/lib/deliveryArea.js)
DELIVERY_CENTER_LAT = float(os.getenv('DELIVERY_CENTER_LAT', '0.9082643'))
DELIVERY_CENTER_LNG = float(os.getenv('DELIVERY_CENTER_LNG', '-77.7904203'))
# El radio vigente vive en StoreSettings (lo edita el admin desde el dashboard);
# este valor solo sirve de semilla inicial y de respaldo.
DELIVERY_RADIUS_KM = float(os.getenv('DELIVERY_RADIUS_KM', '1.5'))
