# Generated by Django 6.0 on 2026-09-23 17:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', help_text='Texto de la página pública del concurso', verbose_name='Descripción')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Fecha del concurso')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Hora del concurso')),
                ('prize', models.CharField(blank=True, default='', help_text='Vacío mientras no esté definido: la app anuncia que pronto se revela', max_length=200, verbose_name='Premio')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10, verbose_name='Valor de la inscripción')),
                ('min_age', models.PositiveSmallIntegerField(default=18, verbose_name='Edad mínima')),
                ('requires_instagram_follow', models.BooleanField(default=True, verbose_name='Exige seguir a Frostbyte en Instagram')),
                ('payment_instructions', models.TextField(default='Paga la inscripción en la barra de Frostbyte y lleva tu cédula: ahí confirmamos tu pago y tu edad.', verbose_name='Instrucciones de pago')),
                ('is_published', models.BooleanField(default=False, help_text='Apagado, la página pública y el anuncio de la carta no existen', verbose_name='Visible en la app')),
                ('registrations_open', models.BooleanField(default=False, verbose_name='Inscripciones abiertas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Consecutivo dentro del concurso; lo dice el cliente en la barra', verbose_name='Número de inscripción')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=20, verbose_name='Celular')),
                ('instagram_handle', models.CharField(max_length=30, verbose_name='Usuario de Instagram')),
                ('costume', models.CharField(blank=True, default='', help_text='Opcional: de qué piensa venir', max_length=120, verbose_name='Disfraz')),
                ('declared_adult', models.BooleanField(default=False, verbose_name='Declaró ser mayor de edad')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagó')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('follows_instagram', models.BooleanField(default=False, verbose_name='Sigue en Instagram')),
                ('instagram_checked_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='pending', editable=False, help_text='Se calcula solo a partir del pago, Instagram y la cancelación', max_length=20, verbose_name='Estado')),
                ('staff_notes', models.TextField(blank=True, default='', verbose_name='Notas del staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='contests.contest', verbose_name='Concurso')),
                ('instagram_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Instagram revisado por')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pago registrado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['contest', 'number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cancelled', False)), fields=('contest', 'user'), name='contest_entry_one_active_per_user'), models.UniqueConstraint(fields=('contest', 'number'), name='contest_entry_unique_number')],
            },
        ),
    ]
