# Generated by Django 6.0 on 2026-10-02 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_concurso_disfraces_halloween'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(verbose_name='Visitante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='contests.contest', verbose_name='Concurso')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Visita a la página del concurso',
                'verbose_name_plural': 'Visitas a la página del concurso',
                'constraints': [models.UniqueConstraint(fields=('contest', 'visitor_id'), name='contest_visit_unique_visitor')],
            },
        ),
    ]
