# Generated by Django 6.0 on 2026-05-30 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, unique=True, verbose_name='Letra')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['display_order', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=200)),
                ('reward', models.CharField(help_text='Texto, p.ej. "+25 pts"', max_length=40)),
                ('kind', models.CharField(choices=[('first_prediction', 'Primer pronóstico'), ('exact_scores', 'Marcadores exactos'), ('team_matches', 'Partidos de un equipo'), ('streak', 'Racha de aciertos'), ('group_stage_complete', 'Fase de grupos completa'), ('invite', 'Invitar amigos')], max_length=30)),
                ('target', models.PositiveIntegerField(default=1, verbose_name='Meta')),
                ('bonus_points', models.PositiveIntegerField(default=0, help_text='Puntos que suma al ranking al completarse')),
                ('param', models.CharField(blank=True, help_text='p.ej. código de equipo "COL"', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Misión',
                'verbose_name_plural': 'Misiones',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('is_keeper', models.BooleanField(default=False, verbose_name='Arquero')),
                ('api_player_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mundial 2026', max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(default='mundial-2026', max_length=120, unique=True)),
                ('kickoff', models.DateTimeField(verbose_name='Pitazo inicial')),
                ('prize', models.CharField(default='$500.000', max_length=120, verbose_name='Premio')),
                ('prize_note', models.CharField(blank=True, default='En efectivo · un solo ganador', max_length=200)),
                ('api_league_id', models.PositiveIntegerField(default=1, verbose_name='API-Football league id')),
                ('api_season', models.PositiveIntegerField(default=2026, verbose_name='API-Football season')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-is_active', '-kickoff'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=40)),
                ('hint', models.CharField(blank=True, max_length=120)),
                ('points', models.PositiveIntegerField(default=0)),
                ('award_type', models.CharField(choices=[('team', 'Selección'), ('player', 'Jugador'), ('keeper', 'Arquero')], max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('resolved_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='polla.player')),
            ],
            options={
                'verbose_name': 'Mención',
                'verbose_name_plural': 'Menciones',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('iso2', models.CharField(blank=True, max_length=8, verbose_name='ISO-2 (bandera)')),
                ('confederation', models.CharField(blank=True, choices=[('UEFA', 'UEFA'), ('CONMEBOL', 'CONMEBOL'), ('CONCACAF', 'CONCACAF'), ('CAF', 'CAF'), ('AFC', 'AFC'), ('OFC', 'OFC')], max_length=10)),
                ('is_host', models.BooleanField(default=False, verbose_name='Anfitrión')),
                ('recent_form', models.JSONField(blank=True, default=list, help_text='Forma reciente: lista como ["w","w","d","l","w"]')),
                ('api_team_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='polla.group')),
            ],
            options={
                'verbose_name': 'Selección',
                'verbose_name_plural': 'Selecciones',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='polla.team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='N.º de partido')),
                ('slug', models.SlugField(help_text='ID estable, p.ej. m1', max_length=20, unique=True)),
                ('stage', models.CharField(choices=[('group', 'Fase de grupos'), ('r32', 'Dieciseisavos'), ('r16', 'Octavos'), ('qf', 'Cuartos'), ('sf', 'Semifinal'), ('third', 'Tercer puesto'), ('final', 'Final')], default='group', max_length=10)),
                ('round_label', models.CharField(blank=True, max_length=40, verbose_name='Jornada/Ronda')),
                ('home_placeholder', models.CharField(blank=True, help_text='p.ej. "1A"', max_length=40)),
                ('away_placeholder', models.CharField(blank=True, max_length=40)),
                ('kickoff', models.DateTimeField(verbose_name='Hora (UTC)')),
                ('venue_city', models.CharField(blank=True, max_length=80)),
                ('venue_stadium', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('upcoming', 'Próximo'), ('live', 'En vivo'), ('finished', 'Finalizado')], default='upcoming', max_length=10)),
                ('minute', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minuto')),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('api_fixture_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='polla.group')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='polla.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='polla.team')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['kickoff', 'number'],
            },
        ),
        migrations.CreateModel(
            name='AwardPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('scored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='polla.award')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polla_award_picks', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='polla.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='polla.team')),
            ],
            options={
                'verbose_name': 'Elección de mención',
                'verbose_name_plural': 'Elecciones de menciones',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='award',
            name='resolved_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='polla.team'),
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='polla.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polla_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de misión',
                'verbose_name_plural': 'Progreso de misiones',
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Puntos totales')),
                ('match_points', models.PositiveIntegerField(default=0)),
                ('award_points', models.PositiveIntegerField(default=0)),
                ('mission_points', models.PositiveIntegerField(default=0)),
                ('exact_hits', models.PositiveIntegerField(default=0)),
                ('correct_hits', models.PositiveIntegerField(default=0)),
                ('predicted', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polla_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puntaje de usuario',
                'verbose_name_plural': 'Puntajes de usuarios',
                'ordering': ['-points', '-exact_hits'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField()),
                ('away_score', models.PositiveIntegerField()),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('is_exact', models.BooleanField(default=False)),
                ('is_correct_outcome', models.BooleanField(default=False)),
                ('scored', models.BooleanField(default=False, help_text='Ya se calculo el puntaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='polla.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polla_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pronóstico',
                'verbose_name_plural': 'Pronósticos',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'match')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'team')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='polla_match_status_b0ddf6_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['stage'], name='polla_match_stage_608bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['kickoff'], name='polla_match_kickoff_f5fa66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='awardpick',
            unique_together={('user', 'award')},
        ),
        migrations.AlterUniqueTogether(
            name='usermission',
            unique_together={('user', 'mission')},
        ),
    ]
