# Generated by Django 6.0 on 2026-05-31 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='bracket_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BracketPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('scored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_picks', to='polla.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polla_bracket_picks', to=settings.AUTH_USER_MODEL)),
                ('winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='polla.team')),
            ],
            options={
                'verbose_name': 'Pick de bracket',
                'verbose_name_plural': 'Picks de bracket',
                'ordering': ['match__number'],
                'unique_together': {('user', 'match')},
            },
        ),
    ]
