# Generated by Django 6.0 on 2026-05-31 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0002_userscore_bracket_points_bracketpick'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='polla.team', verbose_name='Ganador (avanza)'),
        ),
    ]
