# Generated by Django 6.0 on 2026-06-04 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import IntegrityError, migrations, models


def backfill_referral_codes(apps, schema_editor):
    """Asigna un código de invitación único a cada UserScore existente.

    Corre con el modelo histórico (sin el override de ``save``), por eso usa
    el helper puro y maneja la unicidad reintentando ante colisión.
    """
    from apps.polla.models import generate_referral_code

    UserScore = apps.get_model("polla", "UserScore")
    for score in UserScore.objects.filter(referral_code__isnull=True).iterator():
        for _ in range(6):
            score.referral_code = generate_referral_code()
            try:
                score.save(update_fields=["referral_code"])
                break
            except IntegrityError:
                score.referral_code = None
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0003_match_winner_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True, verbose_name='Código de invitación'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='referral_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified', models.BooleanField(default=False, help_text='True cuando el invitado ya hizo su primer pronóstico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('invitee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_source', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_referral_codes, migrations.RunPython.noop),
    ]
