# Generated by Django 6.0 on 2026-06-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0004_userscore_referral_code_userscore_referral_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='awards_lock_at',
            field=models.DateTimeField(blank=True, help_text="Fecha/hora (UTC) en que se cierran TODAS las menciones. Vacío = solo se bloquean al marcarse 'resuelta'.", null=True, verbose_name='Cierre de menciones'),
        ),
    ]
