# Generated by Django 6.0 on 2026-06-11 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0005_tournament_awards_lock_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='Puesto')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='Goles')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='Asistencias')),
                ('appearances', models.PositiveIntegerField(default=0, verbose_name='PJ')),
                ('photo_url', models.URLField(blank=True)),
                ('api_player_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='polla.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='polla.team')),
            ],
            options={
                'verbose_name': 'Goleador',
                'verbose_name_plural': 'Goleadores',
                'ordering': ['rank'],
            },
        ),
    ]
