# Generated by Django 6.0 on 2026-06-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0006_topscorer'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='statistics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
