# Generated by Django 6.0 on 2026-06-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0007_match_events_match_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='h2h',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='match',
            name='h2h_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
