# Generated by Django 6.0 on 2026-06-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0008_match_h2h_match_h2h_fetched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dorsal'),
        ),
        migrations.AddField(
            model_name='player',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'Arquero'), ('DF', 'Defensa'), ('MF', 'Mediocampista'), ('FW', 'Delantero')], max_length=2, verbose_name='Posición'),
        ),
    ]
