# Generated by Django 6.0 on 2026-06-17 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0009_player_age_player_number_player_photo_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GranizadoReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True, verbose_name='Código')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Emitido')),
                ('expires_at', models.DateTimeField(verbose_name='Vence')),
                ('redeemed', models.BooleanField(default=False, verbose_name='Entregado')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado el')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granizado_rewards', to='polla.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granizado_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Granizado ganado',
                'verbose_name_plural': 'Granizados ganados',
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'match')},
            },
        ),
    ]
