# Generated by Django 6.0 on 2026-01-30 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIImageGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image_url', models.URLField(blank=True, max_length=500)),
                ('reference_image_url', models.URLField(blank=True, max_length=500)),
                ('generated_image_url', models.URLField(blank=True, max_length=500)),
                ('temp_original_path', models.CharField(blank=True, max_length=500)),
                ('temp_reference_path', models.CharField(blank=True, max_length=500)),
                ('temp_generated_path', models.CharField(blank=True, max_length=500)),
                ('user_prompt', models.TextField(blank=True)),
                ('transparent_background', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('saved', 'Guardado en R2')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_saved_to_r2', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generated_images', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
