# Generated by Django 6.0 on 2026-01-29 22:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationUsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.IntegerField(default=10, verbose_name='Límite Mensual')),
                ('used_this_month', models.IntegerField(default=0, verbose_name='Usado Este Mes')),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Costo Total (USD)')),
                ('last_reset', models.DateField(auto_now_add=True, verbose_name='Último Reset')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quota', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cuota de Uso IA',
                'verbose_name_plural': 'Cuotas de Uso IA',
            },
        ),
        migrations.CreateModel(
            name='AIImageGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='ai_generations/originals/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen Original')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='ai_generations/references/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen de Referencia')),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='ai_generations/results/%Y/%m/', verbose_name='Imagen Generada')),
                ('user_prompt', models.TextField(blank=True, max_length=500, verbose_name='Prompt del Usuario')),
                ('transparent_background', models.BooleanField(default=True, verbose_name='Fondo Transparente')),
                ('full_prompt', models.TextField(blank=True, verbose_name='Prompt Completo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('generation_time_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tiempo de Generación (segundos)')),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Costo (USD)')),
                ('openai_model', models.CharField(default='gpt-image-1.5', max_length=50, verbose_name='Modelo de OpenAI')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generated_images', to='products.product', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Generación de Imagen IA',
                'verbose_name_plural': 'Generaciones de Imágenes IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_generato_user_id_b00a2d_idx'), models.Index(fields=['status'], name='ai_generato_status_841885_idx')],
            },
        ),
    ]
