# Generated by Django 6.0 on 2026-03-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimagegeneration',
            name='ai_model',
            field=models.CharField(default='gemini-3-pro-image-preview', help_text='Modelo de IA usado para la generacion', max_length=50),
        ),
    ]
