# Generated by Django 6.0 on 2026-01-18 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('icon', models.CharField(default='MoreHorizontal', help_text='Nombre del icono de Lucide React', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='gray', help_text='Color para UI (ej: blue, green, red)', max_length=20, verbose_name='Color')),
                ('is_recurring_default', models.BooleanField(default=False, help_text='Indica si esta categoria tipicamente tiene gastos recurrentes', verbose_name='Es recurrente por defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de gasto',
                'verbose_name_plural': 'Categorias de gastos',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpenseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del gasto recurrente', max_length=200, verbose_name='Nombre')),
                ('description', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto estimado')),
                ('recurrence_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='Tipo de recurrencia')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Para gastos mensuales (1-31)', null=True, verbose_name='Dia del mes')),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='Para gastos semanales (0=Lunes, 6=Domingo)', null=True, verbose_name='Dia de la semana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_generated_at', models.DateField(blank=True, null=True, verbose_name='Ultima generacion')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Proxima fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_templates', to='expenses.expensecategory', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expense_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de gasto recurrente',
                'verbose_name_plural': 'Plantillas de gastos recurrentes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperationalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numero de gasto')),
                ('description', models.CharField(help_text='Descripcion del gasto', max_length=500, verbose_name='Descripcion')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto en COP', max_digits=12, verbose_name='Monto')),
                ('expense_date', models.DateField(help_text='Fecha en que se realizo o se debe realizar el gasto', verbose_name='Fecha del gasto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('check', 'Cheque'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('other', 'Otro')], max_length=20, verbose_name='Metodo de pago')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('reference_number', models.CharField(blank=True, help_text='Numero de factura, recibo, etc.', max_length=100, verbose_name='Numero de referencia')),
                ('receipt_url', models.URLField(blank=True, help_text='Enlace a imagen del recibo o factura', verbose_name='URL del recibo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Es recurrente')),
                ('recurrence_period', models.CharField(choices=[('none', 'No recurrente'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], default='none', max_length=20, verbose_name='Periodo de recurrencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('recurring_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expenses', to='expenses.recurringexpensetemplate', verbose_name='Plantilla recurrente')),
            ],
            options={
                'verbose_name': 'Gasto operativo',
                'verbose_name_plural': 'Gastos operativos',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date'], name='expenses_op_expense_0ed194_idx'), models.Index(fields=['status'], name='expenses_op_status_2a7319_idx'), models.Index(fields=['category'], name='expenses_op_categor_8c4906_idx')],
            },
        ),
    ]
