# Generated by Django 6.0 on 2026-08-19 23:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_seed_businesses'),
        ('expenses', '0002_expense_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='kind',
            field=models.CharField(choices=[('operational', 'Gasto operativo'), ('investment', 'Inversion')], default='operational', help_text='Tipo por defecto de los gastos de esta categoria: gasto corriente o inversion', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='operationalexpense',
            name='kind',
            field=models.CharField(choices=[('operational', 'Gasto operativo'), ('investment', 'Inversion')], default='operational', help_text='Gasto corriente (resta del margen) o inversion (compra algo que dura)', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='operationalexpense',
            index=models.Index(fields=['kind', 'expense_date'], name='expenses_op_kind_idx'),
        ),
    ]
