# Generated by Django 6.0 on 2026-04-11 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_add_show_extras_to_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de recetario',
                'verbose_name_plural': 'Categorías de recetario',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Media'), ('hard', 'Difícil')], default='medium', max_length=20, verbose_name='Dificultad')),
                ('prep_time', models.PositiveIntegerField(blank=True, help_text='Tiempo en minutos', null=True, verbose_name='Tiempo de preparación')),
                ('servings', models.CharField(blank=True, help_text='Ej: 1 vaso de 16oz', max_length=100, verbose_name='Porciones')),
                ('tips', models.TextField(blank=True, verbose_name='Tips y notas')),
                ('video_url', models.URLField(blank=True, verbose_name='URL de video')),
                ('image_url', models.URLField(blank=True, verbose_name='URL de imagen principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_books', to='products.product', verbose_name='Producto')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_books', to='products.productvariant', verbose_name='Variante de producto')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recetarios.recipecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Recetario',
                'verbose_name_plural': 'Recetarios',
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeBookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='URL de imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recetarios.recipebook', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Imagen de receta',
                'verbose_name_plural': 'Imágenes de receta',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeBookIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('quantity', models.CharField(blank=True, help_text='Ej: 2 cucharadas, 200ml, al gusto', max_length=100, verbose_name='Cantidad')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unidad')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Opcional')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recetarios.recipebook', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Ingrediente de receta',
                'verbose_name_plural': 'Ingredientes de receta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeBookStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Número de paso')),
                ('instruction', models.TextField(verbose_name='Instrucción')),
                ('image_url', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('tip', models.CharField(blank=True, max_length=500, verbose_name='Tip')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recetarios.recipebook', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Paso de receta',
                'verbose_name_plural': 'Pasos de receta',
                'ordering': ['step_number'],
                'unique_together': {('recipe', 'step_number')},
            },
        ),
    ]
