# Generated by Django 6.0 on 2026-04-11 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_show_extras_to_category'),
        ('recetarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebook',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_books', to='products.category', verbose_name='Categoría'),
        ),
        migrations.DeleteModel(
            name='RecipeCategory',
        ),
    ]
